"""remove cart_id attribute

Revision ID: d39c084a6e53
Revises: 
Create Date: 2023-10-11 00:29:09.289457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39c084a6e53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discounts')
    op.drop_table('payments')
    op.drop_column('cart_items', 'cart_item_id')
    op.drop_column('carts', 'cart_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('cart_id', sa.INTEGER(), nullable=False))
    op.add_column('cart_items', sa.Column('cart_item_id', sa.INTEGER(), nullable=False))
    op.create_table('payments',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discounts',
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('percentage', sa.INTEGER(), nullable=False),
    sa.Column('expiration_date', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
